### ISSUE TITLE
Delly won't call any structural variants when the "R-" count dominates

### ISSUE THREAD

**Issue by SSunkara** [tobiasrausch/delly#27]
Hi Tobias,

It seems that Delly most definitely won't call "any" structural variants if the FR- and RF- population is higher than the R+, F+ or F- pools.

I have almost never had a problem calling known gene-fusion events even with a very high proportion of the "R-" species, as long as the counts are still lower than the R+ pools. The only structural variants of interest to me are gene fusion events that occur over large distances (>10 Mb or so).

I still don't understand this very well, but any insights into why Delly completely draws a blank when the R- pools have the highest counts? 

Attached is a plot with insert-sizes on the x-axis and counts on the y-axis.

![s5_17178](https://cloud.githubusercontent.com/assets/3697239/9648529/795059b0-519e-11e5-96fd-3bc42206a796.png)

Strand specific orientations
FF+ (0): 17528
FF- (1): 25675
FR+ (2): 6909342
FR- (3): 19978535
RF+ (4): 7492191
RF- (5): 22308715
RR+ (6): 4996
RR- (7): 4686

Strand independent orientations
F+ (0): 22524
F- (1): 30361
R+ (2): 14401533
R- (3): 42287250

Thanks a lot,
Sirisha

**Comment by tobiasrausch** [comment]
Hi Sirisha,

R- is the default read-pair orientation in illumina's long-insert mate-pair libraries (insert size commonly 3kbp-6kbp or even larger). One drawback of these libraries is that they create chimeric read pairs in R+ orientation that have an insert size <1kbp. These chimeric read pairs create tons of SV calls for a mate-pair library and because of that Delly cleans all R+ pairs if R- is the most common orientation.

Best, Tobias

**Comment by SSunkara** [comment]
Hi Tobias,

Sorry, I should have elaborated some more... I am currently using only short-insert paired-end libraries, with an acceptable tight distribution (coefficient of variation is: < 0.2; median insert size 124 and median abs.deviation 23). 

The mapped data very clearly shows the specific gene fusion event (ALK-EML4), both from the paired-end insert estimates, and the split reads. And that is the only time Delly seems to miss out on detecting the event.

Any chance that you could implement calling variants even when the R- dominates (and only the paired-end library is used), as long as there is a user option to specify what library type is being used? Typically, I have my own library QC metrics in place, and would attempt calling SVs in a cautious way.

Thanks so much, Tobias.
Sirisha

**Comment by tobiasrausch** [comment]
Hi Sirisha,

That's a good point to remove R+ pairs only if it is indeed a mate-pair library of larger insert size. I am checking now if the insert size of the R- pairs is indeed >1kbp otherwise I keep the R+ pairs. Can you please check if it is working now I don't think I have any test data for your case? I just checked-in the patch in the delly repository.

Thanks, Tobias

**Comment by SSunkara** [comment]
Awesome! Will keep you posted..

**Comment by SSunkara** [comment]
Thanks for that fix,Tobias. It worked well!
