### ISSUE TITLE
Run for a large number of WGS samples

### ISSUE THREAD

**Issue by sehrrot** [tobiasrausch/delly#33]
Hi Tobias,

Thanks for the nice tool. I tried to post this question on the google group but cannot get permission for that, so leave a question here.

I plan to run a large number of ~70 WGS trios using Delly. When I ran them with chr22 bam (using multi thread option), it worked properly. But when it comes to the entire genome, I don't have any idea for computational requirement. Also, I am not too sure calling accuracy between multiple samples vs. single sample run. Could I get your advice? Or can I probably run them by trios, or subset of samples?

**Comment by tobiasrausch** [comment]
The Delly workflow to analyze hundreds of samples is below:

(1) Discover SVs in batches (e.g. one trio at a time)

(2) From all batch runs create a merged SV site list, e.g.:

> zcat del_batch1.vcf.gz | head -n 500 | grep "^#" | cut -f 1-8 > DEL.vcf
> zcat del_batch*.vcf.gz | grep -v "^#" | cut -f 1-8 | grep -v -P "LowQual\tIMPRECISE" | awk 'BEGIN {OFS="\t";} { $3=sprintf("DEL%08d", NR); print $0;}' | vcf-sort -c >> DEL.vcf
> vcf-validator DEL.vcf

(3) Re-genotype this DEL.vcf in all samples as explained here https://github.com/tobiasrausch/svcatalog and create a DEL.regeno.vcf file with genotypes for all your samples

(4) Filter DEL.regeno.vcf using cnvClassifier if you are interested in germline SVs. This script also takes care of redundant SVs (same SV discovered in multiple batch runs with slightly different coordinates). You may want to adapt this script a bit in your case because the trio setup gives you additional power to filter SVs.

If the merged site list in DEL.vcf has more than 200,000 sites you may want to implement some ad hoc filters in (2) and collapse deletion calls that are almost identical (e.g. breakpoints differ by <25bp) among the batch runs because common deletions will be discovered in every single batch. Here is a quick and dirty way of doing this “collapsing” of redundant deletions already at the site list creation:

zcat del_batch*.vcf.gz | grep -v "^#" | cut -f 1-8 | grep -v -P "LowQual\tIMPRECISE" | awk '{print $0"\t"(int($2/10)*10)"\t"length($8);}' | sort -k1,1 -k9,9g -k10,10gr | awk '{if (OLD != $1"-"$9) { print $0; } ; OLD=$1"-"$9;}' | cut -f 1-8 |  awk 'BEGIN {OFS="\t";} { $3=sprintf("DEL%08d", NR); print $0;}' | vcf-sort -c >> DEL.vcf

Best, Tobias
