### ISSUE TITLE
Please vendor dependencies instead of git submodules

### ISSUE THREAD

**Issue by serverhorror** [tobiasrausch/delly#35]
Hi,

please vendor the dependencies instead of making submodules. For a packager it is quite hard to work with the current build system you have.

The current releases on github are actually more harmful than helpful because after downloading it one ends up with basically broken code.

This is also in reference to: #32

**Comment by tobiasrausch** [comment]
Unfortunately, there seems to be no way to include submodules in these automatic release packages. I indeed could vendor the dependencies but the downside of this approach is that it requires a manual download and copy process whenever the external library is updated. Since this happened frequently lately for htslib and also brought some nice additional features (as, for instance, cram support) I am a bit undecided what is the better option in the long term.

**Comment by serverhorror** [comment]
Hi,

I know that it requires manual intervention. Then again, in my opinion, so do submodules. After all they refer to a specific tag.

I'm suggesting vendoring because right now you only have tags. I'd consider a "release" something that I can download and that is self contained enough to build if all external dependencies are fullfilled.

Currently the Makefile has no option of specifying that htslib and friends already exist somewhere, so that leaves two options I can think of: Rework the Makefile to be more dynamic (personally l like CMake way better but then again the occasional coding I do makes me a novice at best) or provide self contained releases. I think the latter is way less work by just vendoring the libs.

Would you accept a merge request where I would prepare the vendoring options? (I promise to put a thought or two in it to make updating dependencies as painless as possible) :)

**Comment by tobiasrausch** [comment]
The Makefile does allow specifying external libraries, you just need to set the SEQTK_ROOT and BOOST_ROOT environment variables. Only if these variables are not set delly looks for the submodules.

SEQTK_ROOT ?= ${PWD}/src/htslib/
BOOST_ROOT ?= ${PWD}/src/modular-boost
