### ISSUE TITLE
v0.7.3 Segmentation fault

### ISSUE THREAD

**Issue by jem569** [tobiasrausch/delly#43]
Hi,

The new features in v0.7.3 sound great, however I'm getting seg faults when I try to run input that worked with v0.7.2.

Build on linux(CentOS) HPC cluster using:

git clone --recursive https://github.com/tobiasrausch/delly.git
cd delly/
make all

Any ideas?

(duplicate post on delly-users)
Thanks,
Jacob

**Comment by tobiasrausch** [comment]
Hi,

If you can share a slice of the data that re-produces the error I am happy to take a look. If this is confidential data you can also run delly yourself in debug mode.

make DEBUG=1 src/delly

Best, Tobias

**Comment by jem569** [comment]
Hi Tobias,

In debug mode the program seems to hang indefinitely at the point that would usually lead to a segmentation fault.

The following bam file reproduces the issue:
https://www.dropbox.com/sh/9q8md8fijiyf0zh/AAArRsg9R830XVkcwPRAkRfua?dl=0
alignment is to hg38

Interestingly I tried smaller slices (10,000 and 100,000 reads), but it wasn't until 1,000,000 reads that the error was reproduced.

Thanks,
Jacob.

**Comment by tobiasrausch** [comment]
Thanks for sharing the BAM file. I downloaded it so you can remove it.

I tried the pre-compiled v0.7.3 binaries and all jobs worked fine:

delly_v0.7.3_linux_x86_64bit call -t DEL -g hg38.fa test.bam
delly_v0.7.3_linux_x86_64bit call -t DUP -g hg38.fa test.bam
delly_v0.7.3_linux_x86_64bit call -t INV -g hg38.fa test.bam
delly_v0.7.3_linux_x86_64bit call -t TRA -g hg38.fa test.bam
delly_v0.7.3_linux_x86_64bit call -t INS -g hg38.fa test.bam

You probably used the latest Delly github code instead of the tagged v0.7.3 version. This code can be occasionally a bit more unstable. The latest code, however, also seems to be fine - I cannot reproduce this segmentation fault. Please try with the latest code or v0.7.3 and let me know if you still have problems.

-Tobias

**Comment by jem569** [comment]
Thanks for testing that.

The binaries seem to work for me, not sure why i couldn't build it properly on my system though.

Regards,
Jacob.
