### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by GKerdivel** [tobiasrausch/delly#48]
Hi

I got segmentation fault with the latest delly Version: 0.7.3

0%   10   20   30   40   50   60   70   80   90   100%
|----|----|----|----|----|----|----|----|----|----|
**********
 18187 Segmentation fault      (core dumped) 

OS: Ubuntu 15.1

Command :
/home/gwenneg/bin/delly/src/delly call -t DEL -q 13 -o $OUTDIR/$SAMPLENAME.delly.bcf -g $REF $TMPDIR/$TUMOR.sorted.bam $TMPDIR/$NORMAL.sorted.bam

My bam files are sorted and indexed

Thank's for helping

Gwenneg

**Comment by tobiasrausch** [comment]
Have you run Picard ValidateSamFile already? Segmentation faults are usually due to incorrect read-groups.

If the BAM file is fine you can run Delly also in Debug mode using make DEBUG=1 src/delly or if you can reproduce the error with a small BAM slice that can be shared I am also happy to debug it myself.

**Comment by GKerdivel** [comment]
Thank you for your answer. There is indeed a problem in the BAM file: 
NM tag (nucleotide differences) is missing
I am not exactly sure of how to solve it ?
