### ISSUE TITLE
Questions about DELLY0.7.3

### ISSUE THREAD

**Issue by yuanyuanji** [tobiasrausch/delly#55]
After change my delly to version 0.7.3, I compare the result of v0.7.2 and the new version0.7.3, I was confused about some result, I am appreciated if anyone can answer my questions.

1. new result on vcf file(CE:Consensus sequence entropy), I know it provide accuracy of consensus sequence, however I donot understand how to judge it, the smaller the better? and can anyone give me the range of it?

2. With the same data, I found that the version0.7.2 can got insertion events, but the new version0.7.3  cannot. I test 4 times for different data, and the new version0.7.3 always donot give me any insertion events, but version0.7.2 provide its.

3. I also confused about the filter, is there any change in it. Because I found that with same arguments, 0.7.3version give us more SV events than version0.7.2. Can anyone explain it? I am also interested about the filter mechanism. I try to filter it by genotype (somaticsample:0/1;germlinesample:0/0), but it much larger than you filter, is there anyother codition?

4. about merge. I am confused about it. which condition should I use it ? merge different samples? or others? can I use it to merge different types of SV files(bcf)?

Thanks a lot

**Comment by tobiasrausch** [comment]
INFO:CE:
INFO:CE is just the entropy of the consensus. Lower values usually indicate that the consensus is highly repetitive, something like CTCTCTCT...   Repeats can cause false positive SVs so in that sense higher INFO:CE values tend to be more reliable SV breakpoints.

Insertions:
v0.7.5 does call insertions but only by re-aligning soft-clipped reads. I stopped calling insertions from paired-ends & mate-pairs because this was too error prone (high FDR).

Delly filter:
Delly's somatic filter has several additional parameters for a list of confident somatic SVs such as a minimum required coverage, a maximum fractional ALT support in the control, a minimum fractional ALT support in the tumor, SV size filters, etc. - all of these filters can be adjusted on the command line.

Delly merge:
SVs are often called imprecisely and thus, you cannot just merge SVs from different samples using the exact same coordinates but rather have to define "identity of SVs" in terms of reciprocal overlap and breakpoint offset. That's what delly merge does.

Please consider using the delly-users mailing list for these kind of usage questions in the future.

https://groups.google.com/forum/#!forum/delly-users

Thanks, Tobias
